---
global:
  resolve_timeout: 1m
route:
  receiver: 'gmail-notifications'
receivers:
  - name: 'gmail-notifications'
    email_configs:
    - to: monitoringinstances@gmail.com
      from: monitoringinstances@gmail.com
      smarthost: smtp.gmail.com:587
      auth_username: monitoringinstances@gmail.com
      auth_identity: monitoringinstances@gmail.com
      auth_password: password
      send_resolved: true